### ISSUE TITLE
Fatal Error when going to mydomain.com/sitemap.xml

### ISSUE THREAD

**Issue by MichaelJJames** [Cyber-Duck/Silverstripe-SEO#1]
Hi, 

Im getting the following error when going to view the sitemap mydomain.com/sitemap.xml

PHP Fatal error: Call to a member function getSitemapXML() on null in httpdocs/seo/code/core/SEO.php on line 143

Thanks
Michael

**Comment by Andrew-Mc-Cormack** [comment]
Have you added SEO::init() to your Page_Controller? - https://github.com/Cyber-Duck/Silverstripe-SEO/tree/master/docs/installation#controller

**Comment by MichaelJJames** [comment]
Hi Andrew, 

Thanks for your reply i added SEO::init() to my Page Controller and it works now.

Thanks
