### ISSUE TITLE
Requirements issue when using Silverstripe 4.1 in combination with public directory

### ISSUE THREAD

**Issue by lars-lemon8** [Cyber-Duck/Silverstripe-SEO#14]
Hi,

Can't seem to find any docs on it, but the extra_requirements_css in CMS.yml does not seem to play nice with SS 4.1 i.c.w. the public folder. 

Right now it reads :
`resources/cyber-duck/silverstripe-seo/assets/css/seo.css`

After exposing the assets to the public folder, the needed CSS file will be situated in 
/public/resources/**vendor**/cyber-duck/silverstripe-seo/assets/css/seo.css

**Comment by renskorswagen** [comment]
#15
