### ISSUE TITLE
Absolute URLs needed for OG tags

### ISSUE THREAD

**Issue by lars-lemon8** [Cyber-Duck/Silverstripe-SEO#2]
Thanks for your work on this module ! 

It seems the SEO module produces relative URL's for social images. 

<meta property="og:image" content="/assets/xxxxxx.png">

Is there any way to produce absolute URL's ?

**Comment by Andrew-Mc-Cormack** [comment]
This commit will change the tags to use the absolute URL. Will be released as part of 1.0.6 over the weekend.

https://github.com/Cyber-Duck/Silverstripe-SEO/commit/46360589e315822f8abb3fab0ca94694382abdb1

**Comment by lars-lemon8** [comment]
Wow... !! That was fast. Thanks a lot !   ;-)
