### ISSUE TITLE
Error for pagination in blog

### ISSUE THREAD

**Issue by Misagh90** [Cyber-Duck/Silverstripe-SEO#22]
Hi,
When i try next page or page number in blog i see this error
![screenshot 71](https://user-images.githubusercontent.com/6697222/50573214-93823780-0de4-11e9-8fe1-7c58675dba13.png)
I changed the (`CurrentPage() == 2`) in these code (`if($this->CurrentPage() == 2) {
            $url = $this->request->getURL(false);`) in src\ORM\SeoPaginatedList.php into another number(e.g. `CurrentPage() == 0` or `CurrentPage() == 1000`) then it's working fine

**Comment by Andrew-Mc-Cormack** [comment]
Are you using a custom controller for the blog?

**Comment by Misagh90** [comment]
No, i only add a $many_many filed in my blog post.

**Comment by Andrew-Mc-Cormack** [comment]
Fixed on develop branch, will be in a release tomorrow. Think the issue is the request property is not an  object but an array. Cant remember exactly but it is fixed by a custom blog controller also by calling parent::index(); in the custom blog controller index method.
