### ISSUE TITLE
Path to seo.css not correct

### ISSUE THREAD

**Issue by J-Pielage** [Cyber-Duck/Silverstripe-SEO#28]
When installing this module on newer SilverStripe versions I always get the following message: 
`[User Notice] File resources/vendor/cyber-duck/silverstripe-seo/assets/css/seo.css does not exist`

For now I copied the seo.css file into the direction path from the warning `resources/vendor/cyber-duck/silverstripe-seo/assets/css/` But it would be nice if the path can be autogenerated into a `_resources` folder.

**Comment by pinkp** [comment]
I still get this error unless I make a new folder path.

**Comment by J-Pielage** [comment]
Looks like this one is now fixed!
