### ISSUE TITLE
Settings default OG locale 

### ISSUE THREAD

**Issue by lars-lemon8** [Cyber-Duck/Silverstripe-SEO#3]
I can't seem to figure out how to set the default OGLocale. It always defaults to en_GB.

**Comment by Andrew-Mc-Cormack** [comment]
If you go to the "Page SEO" tab you will see "Open Graph Locale" under "Social Media"

**Comment by lars-lemon8** [comment]
Yeah,  but I'd like to set the default Locale instead of setting it on a page by page basis.

**Comment by lars-lemon8** [comment]
Right now , I'm overwriting the OGLocale() method in my Base Page Controller class.  

Maybe we can use the site default locale instead of a hard-coded value ?

In headtags.ss:
`<meta property="og:locale" content="<% if $OGlocale %>$OGlocale<% else %>en_GB<% end_if %>">`

@Andrew-Mc-Cormack
