### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by peterkoopman** [Cyber-Duck/Silverstripe-SEO#31]
I get this error on initial installation. I have done a dev/build?flush
Expression #1 of ORDER BY clause is not in SELECT list, references column 'lyniate.Page.Priority' which is not in SELECT list; this is incompatible with DISTINCT

![image](https://user-images.githubusercontent.com/3385073/88243951-314e9780-cce6-11ea-878e-ddc4415e851b.png)

**Comment by nickjacobs** [comment]
Do you also have wilr/silverstripe-googlesitemaps installed? Getting rid of this and removing the SiteTree.Priority field solved this one for me...there is a clash with the Priority fields

**Comment by samthejarvis** [comment]
Thanks @nickjacobs. Closing as issue not within scope of this module
