### ISSUE TITLE
Call to undefined method SilverStripe\Config\Collections\CachedConfigCollection::remove()

### ISSUE THREAD

**Issue by sebastiand** [Cyber-Duck/Silverstripe-SEO#35]
The same error that was already reported in #19 occurs again starting from version 4.4.0+.

It was fixed via commit https://github.com/Cyber-Duck/Silverstripe-SEO/commit/3217646e4f39ff481b6d2594db0c705d15eeaf27 (pull request 24).

The bug was then re-introduced via commit https://github.com/Cyber-Duck/Silverstripe-SEO/commit/cd53f5ae48dab5b74edcd9442c0550f556afdc0c where the buggy line `Config::inst()->remove($this->owner->class, 'summary_fields');` in `SeoPageExtension.php` was added again.

I have created a modified fix: 
I added a check if the method `remove()` exists in the owner class, before calling it - inssead of removing the the line altogether.

I will add a pull request towards the develop branch for this, and hope it will be relaesed as a new bugfix version 4.5.2 soon.

**Comment by monkeyfeet** [comment]
Hey has there been any progress on this proposed fix? I'm experiencing this issue on a SS 4.7 installation.

**Comment by sebastiand** [comment]
We´ve been using this fix on 3 productive websites for 5 months now without any issues. Would be happy if this fix would be merged soon :-)

**Comment by sebastiand** [comment]
I´ve updated the fix and pull request to be PHP 8 compatible
See: a28de34553a616c1506e3e1f11219ec62e6bbc83

Any chance this is getting merged soon?

**Comment by ramono** [comment]
Hi @sebastiand thank you for the contribution and sorry for the time it took to look into this, we're taking a bit of time to review all the issues and PRs now.
