### ISSUE TITLE
The 4.6.0 tag breaks dev build

### ISSUE THREAD

**Issue by mooror** [Cyber-Duck/Silverstripe-SEO#44]
After a composer update, the new (but unreleased?) tag 4.6.0 was brought down and the dev/build screen began to display the following error:
![4-6-0-tag-dev-build-error](https://user-images.githubusercontent.com/6110819/167519871-5fff28ae-f844-45a2-a8ee-380f15adc562.png)

I could be wrong, but I think this may have to do with [commit e93f286856bae7dee77150907c16b9c93c6b5600](https://github.com/Cyber-Duck/Silverstripe-SEO/commit/e93f286856bae7dee77150907c16b9c93c6b5600) where the DB fields were changed to MediumText. I've reverted back to version 4.5.4 until this is fixed

**Comment by samthejarvis** [comment]
Hi @mooror thanks for reporting. Technically [this PR](https://github.com/Cyber-Duck/Silverstripe-SEO/commit/45b36f826bff41da862f6460e78759998ba0eabc) brought in the issue but you're on the right lines :) - text/blobs can't be indexed and Title/URLSegment are usually indexed. These will be reverted back to varchars.

**Comment by samthejarvis** [comment]
@mooror 4.6.1 contains the fix for this - please update to this.

**Comment by mooror** [comment]
Thank you @samthejarvis for fixing this I will update to 4.6.1 and report back
