### ISSUE TITLE
Static Publisher problem with meta-tags

### ISSUE THREAD

**Issue by lars-lemon8** [Cyber-Duck/Silverstripe-SEO#7]
Hi,

I'm experiencing problems with Static Publisher in conjunction with the SEO module.

It seems meta-tags the SEO module sets, do not get updated when statically publishing a queue. (all pages get the same meta-tags than the first page in the queue) ..

I've been digging around , but can't seem to find the issue , could be something in the static-publisher as wel.   Wondering whether you run the SEO module in conjunction with the static publisher as well or have any idea where to look ..... 

thnks,
lars

**Comment by Andrew-Mc-Cormack** [comment]
Is this the module? - https://github.com/silverstripe/silverstripe-staticpublisher

**Comment by lars-lemon8** [comment]
Yep.

**Comment by lars-lemon8** [comment]
I don't think this issue is relevant any longer.    ;-)
